pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/2002Umesh/Wipro-Training'
            }
        }

        stage('Build') {
            steps {
                dir('Cucumber_BBD') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('Cucumber_BBD') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Cucumber_BBD') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Cucumber_BBD') {
                    bat 'mvn package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Cucumber_BBD') {
                    bat 'docker build -t cucumber-framework .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('Cucumber_BBD') {
                    bat 'docker run cucumber-framework'
                }
            }
        }
            post {
        always {
            junit '*/target/surefire-reports/.xml'
        }
    }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}